//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Testovaya_ochered
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Участник.
    /// </summary>
    //  *** Start programmer edit section *** (Участник CustomAttributes)

    //  *** End programmer edit section *** (Участник CustomAttributes)
    [BusinessServer("IIS.Testovaya_ochered.УчастникBS, Testovaya_ochered.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [PublishName("Участник")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УчастникE", new string[] {
            "Фамилия as \'Фамилия\'",
            "ДатаВступления as \'Дата вступления\'"})]
    [View("УчастникL", new string[] {
            "Фамилия as \'Фамилия\'",
            "ДатаВступления as \'Дата вступления\'"})]
    public class Участник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private System.DateTime fДатаВступления;
        
        //  *** Start programmer edit section *** (Участник CustomMembers)

        //  *** End programmer edit section *** (Участник CustomMembers)

        
        /// <summary>
        /// Фамилия.
        /// </summary>
        //  *** Start programmer edit section *** (Участник.Фамилия CustomAttributes)

        //  *** End programmer edit section *** (Участник.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                //  *** Start programmer edit section *** (Участник.Фамилия Get start)

                //  *** End programmer edit section *** (Участник.Фамилия Get start)
                string result = this.fФамилия;
                //  *** Start programmer edit section *** (Участник.Фамилия Get end)

                //  *** End programmer edit section *** (Участник.Фамилия Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Участник.Фамилия Set start)

                //  *** End programmer edit section *** (Участник.Фамилия Set start)
                this.fФамилия = value;
                //  *** Start programmer edit section *** (Участник.Фамилия Set end)

                //  *** End programmer edit section *** (Участник.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// ДатаВступления.
        /// </summary>
        //  *** Start programmer edit section *** (Участник.ДатаВступления CustomAttributes)

        //  *** End programmer edit section *** (Участник.ДатаВступления CustomAttributes)
        public virtual System.DateTime ДатаВступления
        {
            get
            {
                //  *** Start programmer edit section *** (Участник.ДатаВступления Get start)

                //  *** End programmer edit section *** (Участник.ДатаВступления Get start)
                System.DateTime result = this.fДатаВступления;
                //  *** Start programmer edit section *** (Участник.ДатаВступления Get end)

                //  *** End programmer edit section *** (Участник.ДатаВступления Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Участник.ДатаВступления Set start)

                //  *** End programmer edit section *** (Участник.ДатаВступления Set start)
                this.fДатаВступления = value;
                //  *** Start programmer edit section *** (Участник.ДатаВступления Set end)

                //  *** End programmer edit section *** (Участник.ДатаВступления Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// Представление для редактирования сущности.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастникE", typeof(IIS.Testovaya_ochered.Участник));
                }
            }
            
            /// <summary>
            /// Списковое представление.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастникL", typeof(IIS.Testovaya_ochered.Участник));
                }
            }
        }
    }
}
