//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Testovaya_ochered
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Участник BS.
    /// </summary>
    //  *** Start programmer edit section *** (УчастникBS CustomAttributes)

    //  *** End programmer edit section *** (УчастникBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class УчастникBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        //  *** Start programmer edit section *** (УчастникBS CustomMembers)

        //  *** End programmer edit section *** (УчастникBS CustomMembers)

        
        //  *** Start programmer edit section *** (OnUpdateУчастник CustomAttributes)

        //  *** End programmer edit section *** (OnUpdateУчастник CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateУчастник(IIS.Testovaya_ochered.Участник UpdatedObject)
        {
            //  *** Start programmer edit section *** (OnUpdateУчастник)

            return new ICSSoft.STORMNET.DataObject[0];
            //  *** End programmer edit section *** (OnUpdateУчастник)
        }
    }
}
